# Use uma imagem base do Java
FROM openjdk:11-jdk

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo pom.xml para o diretório de trabalho
COPY pom.xml .

# Baixe as dependências do Maven
RUN mvn dependency:go-offline -B

# Copie todos os arquivos do projeto para o diretório de trabalho
COPY . .

# Compile o projeto
RUN mvn clean install -DskipTests

# Especifique o comando para executar a aplicação
CMD ["java", "-jar", "caminho-para-o-arquivo-jar-do-seu-projeto.jar"]